---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argo
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-helm
      version: '3.28.0'
  interval: 1m0s
  values:
    global:
      image:
        repository: alinbalutoiu/argocd
    apiVersionOverrides:
      ingress: networking.k8s.io/v1
    server:
      ingress:
        enabled: true
        hosts:
        - argocd.mchum.fun
        annotations:
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/force-ssl-redirect: "true"
      extraArgs:
      - --insecure
