---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argo
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-helm
      version: '3.28.0'
  interval: 1m0s
  values:
    global:
      image:
        repository: alinbalutoiu/argocd
    apiVersionOverrides:
      ingress: networking.k8s.io/v1
    server:
      certificate:
        enabled: true
        domain: argocd.mchum.fun
        issuer:
          kind: ClusterIssuer
          name: selfsigned-clusterissuer
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
        - argocd.mchum.fun
        tls:
        - secretName: argocd-server-tls
          hosts:
          - argocd.mchum.fun
      extraArgs:
      - --insecure  # Ingress handles and terminates SSL