---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-middleware
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster/traefik-middleware
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system

