apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: application-secrets
  namespace: default
spec:
  encryptedData:
    piholePassword: AgDQJ/V1TmTO+683szfLbF1J2RDy9hb5UdOPuNIjOwNb1tahtmoZ1tR5pE7EHaky+aYF3vWW3KqsYgM9SBVfYM4CFbb38w9inUjWOf/9az1jfk3eZEZLFmHNyZYr7G6+zlKkSK+zPOvVvA2L3vDFgUXxjJmihgRzJODf2Vh8xbHU5cc2HdfHDLtdZAFRWHWQU0BKAvmk9RT4UMrz3iQDLAeJv88Byqo369WqLzUS4IIOy2+02Cc6HYNFWtg7Wo2k7JUSvjiWqJ7awyVY1M96NThdW/g8sdJ2Uib6ZIza6yc/HyQ7nGhFwMKzxgtrh7wPobSmBtdkoyjHyc9F3DS7QmQoE1f+gOYxLSab9qBn/71yV0pSjVRHGW1Y02AXDQDX+uoT7YwISppZ7Vee8oci1raPIPvEqJpU8n1ovJ8uzJyN/0fQiLtFGD5cdr6w7VzVF2St99XBTQPyrdSA0yUkknybK7qS1TtuP/mU6MAtuDQNZ128kpX/8QmBgifJVZpLuRNPaaoxtriX8AgY/PmzNpUtqK8aJQCz4cNLAA6xCPuUfNhlfSRwJ/Z+MBtCKV3+gKoI84pG1DGlMSWxbfHxLUURmRO7TB6zKC1uLiVWVlfrjNW+e4T98soO0QZrCovTaFnb8cFCnyTKOnsbxKKlDP/vrXRbE5J1d371+YEBC7zMw6x5StziTyZ2cKiCU2oAWvgD3LnoGbIKZSvLwSBCea9DWyfkGJ6ZR7c=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: application-secrets
      namespace: default

