dnsHostPort:
  enabled: false
serviceDns:
  type: NodePort
  port: 53
serviceWeb:
  http:
    enabled: true
  https:
    enabled: false
virtualHost: pihole.mchum.fun
ingress:
  enabled: true
  hosts:
  - pihole.mchum.fun
adlists:
- https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
regex:
- |
  /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
  /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/
  /^(.+[_.-])?telemetry[_.-]/
  /^adim(age|g)s?[0-9]*[_.-]/
  /^adtrack(er|ing)?[0-9]*[_.-]/
  /^advert(s|is(ing|ements?))?[0-9]*[_.-]/
  /^aff(iliat(es?|ion))?[_.-]/
  /^analytics?[_.-]/
  /^banners?[_.-]/
  /^beacons?[0-9]*[_.-]/
  /^count(ers?)?[0-9]*[_.-]/
  /^mads\./
  /^pixels?[-.]/
  /^stat(s|istics)?[0-9]*[_.-]/
persistentVolumeClaim:
  enabled: false
DNS1: "1.1.1.1"
DNS2: "1.0.0.1"
adminPassword: ""
admin:
  existingSecret: application-secrets
  passwordKey: piholePassword
podDnsConfig:
  enabled: true
  nameservers:
  - 127.0.0.1
  - 1.1.1.1
  - 1.0.0.1